style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/notblessy/bless
  commits:
     filters:
       Type:
         - feature
         - fix
         - refactor
  commit_groups:
     title_maps:
       feature: New Features
       fix: Fixes
       refactor: Code Improvements
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE

